/**
 * EnoLandingPage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { TeamDetailsMessage } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AccountServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    apiAccountCheckInPost(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    apiAccountInfoGet(extraHttpRequestParams?: any): Observable<TeamDetailsMessage>;

    /**
     * Login to the Portal.
     * 
     * @param redirectUri The URL the User will be redirected after succesfull login.
     */
    apiAccountLoginGet(redirectUri?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param redirectUri 
     */
    apiAccountOAuth2RedirectGet(redirectUri?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    apiAccountVpnConfigGet(extraHttpRequestParams?: any): Observable<{}>;

}
