/**
 * EnoLandingPage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface AdminServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param adminSecret 
     * @param teamId 
     */
    apiAdminBootVmGet(adminSecret?: string, teamId?: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param adminSecret 
     */
    apiAdminCtfJsonGet(adminSecret?: string, extraHttpRequestParams?: any): Observable<{}>;

}
