/**
 * EnoLandingPage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A DTO representing General Information about the CTF.
 */
export interface CtfInfoMessage { 
    /**
     * The Title of the CTF.
     */
    title: string;
    /**
     * The StartTime of the CTF.
     */
    ctfStartTime: string;
    /**
     * The EndTime of the CTF.
     */
    ctfEndTime: string;
    /**
     * The Time until Teams have to be registred.
     */
    registrationCloseTime: string;
    /**
     * The Time when the checkin will be available.
     */
    checkInBeginTime: string;
    /**
     * The Time until Teams have to be checked in.
     */
    checkInEndTime: string;
}

