/**
 * EnoLandingPage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type LandingPageVulnboxStatus = 'None' | 'Creating' | 'Created';

export const LandingPageVulnboxStatus = {
    None: 'None' as LandingPageVulnboxStatus,
    Creating: 'Creating' as LandingPageVulnboxStatus,
    Created: 'Created' as LandingPageVulnboxStatus
};

