/**
 * EnoLandingPage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type LandingPageVulnboxStatus = 0 | 1 | 2;

export const LandingPageVulnboxStatus = {
    NUMBER_0: 0 as LandingPageVulnboxStatus,
    NUMBER_1: 1 as LandingPageVulnboxStatus,
    NUMBER_2: 2 as LandingPageVulnboxStatus
};

