/**
 * EnoLandingPage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServiceStatus } from './serviceStatus';


export interface ScoreboardTeamServiceDetails { 
    serviceId?: number;
    attackScore?: number;
    defenseScore?: number;
    serviceLevelAgreementScore?: number;
    serviceStatus?: ServiceStatus;
    message?: string | null;
}

