/**
 * EnoLandingPage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScoreboardTeamServiceDetails } from './scoreboardTeamServiceDetails';


export interface ScoreboardTeam { 
    teamName: string;
    teamId: number;
    logoUrl?: string | null;
    countryCode?: string | null;
    totalScore: number;
    attackScore: number;
    defenseScore: number;
    serviceLevelAgreementScore: number;
    serviceDetails: Array<ScoreboardTeamServiceDetails>;
}

