/**
 * EnoLandingPage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScoreboardService } from './scoreboardService';
import { ScoreboardTeam } from './scoreboardTeam';


export interface Scoreboard { 
    currentRound: number;
    roundLength?: number;
    startTimestamp?: string | null;
    endTimestamp?: string | null;
    dnsSuffix?: string | null;
    services: Array<ScoreboardService>;
    teams: Array<ScoreboardTeam>;
}

