/**
 * EnoLandingPage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScoreboardFirstBlood } from './scoreboardFirstBlood';


export interface ScoreboardService { 
    serviceId?: number;
    serviceName?: string | null;
    flagVariants?: number;
    firstBloods?: Array<ScoreboardFirstBlood> | null;
}

