/**
 * EnoLandingPage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ServiceStatus = 0 | 1 | 2 | 3 | 4 | 5;

export const ServiceStatus = {
    NUMBER_0: 0 as ServiceStatus,
    NUMBER_1: 1 as ServiceStatus,
    NUMBER_2: 2 as ServiceStatus,
    NUMBER_3: 3 as ServiceStatus,
    NUMBER_4: 4 as ServiceStatus,
    NUMBER_5: 5 as ServiceStatus
};

