/**
 * EnoLandingPage
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ServiceStatus = 'INTERNAL_ERROR' | 'OK' | 'RECOVERING' | 'MUMBLE' | 'OFFLINE' | 'INACTIVE';

export const ServiceStatus = {
    InternalError: 'INTERNAL_ERROR' as ServiceStatus,
    Ok: 'OK' as ServiceStatus,
    Recovering: 'RECOVERING' as ServiceStatus,
    Mumble: 'MUMBLE' as ServiceStatus,
    Offline: 'OFFLINE' as ServiceStatus,
    Inactive: 'INACTIVE' as ServiceStatus
};

