// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace EnoLandingPageBackend.Migrations
{
    public partial class m1 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Teams",
                columns: table => new
                {
                    Id = table.Column<long>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    CtftimeId = table.Column<long>(type: "INTEGER", nullable: true),
                    Confirmed = table.Column<bool>(type: "INTEGER", nullable: false),
                    Name = table.Column<string>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Teams", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Teams_Confirmed",
                table: "Teams",
                column: "Confirmed");

            migrationBuilder.CreateIndex(
                name: "IX_Teams_CtftimeId",
                table: "Teams",
                column: "CtftimeId",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Teams");
        }
    }
}
