// <auto-generated />
using System;
using EnoLandingPageBackend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnoLandingPageBackend.Migrations
{
    [DbContext(typeof(LandingPageDatabaseContext))]
    [Migration("20201121174204_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EnoLandingPageCore.Database.LandingPageTeam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CtftimeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalAddress")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HetznerServerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPassword")
                        .HasColumnType("TEXT");

                    b.Property<int>("VulnboxStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Confirmed");

                    b.HasIndex("CtftimeId")
                        .IsUnique();

                    b.ToTable("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
