// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace EnoLandingPageBackend.Migrations
{
    public partial class m1 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Teams",
                columns: table => new
                {
                    Id = table.Column<long>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    CtftimeId = table.Column<long>(type: "INTEGER", nullable: true),
                    Confirmed = table.Column<bool>(type: "INTEGER", nullable: false),
                    Name = table.Column<string>(type: "TEXT", nullable: false),
                    VulnboxId = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Teams", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Vulnboxes",
                columns: table => new
                {
                    Id = table.Column<long>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    VulnboxStatus = table.Column<int>(type: "INTEGER", nullable: false),
                    ExternalAddress = table.Column<string>(type: "TEXT", nullable: true),
                    HetznerServerId = table.Column<long>(type: "INTEGER", nullable: true),
                    RootPassword = table.Column<string>(type: "TEXT", nullable: true),
                    LandingPageTeamId = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Vulnboxes", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Vulnboxes_Teams_LandingPageTeamId",
                        column: x => x.LandingPageTeamId,
                        principalTable: "Teams",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Teams_Confirmed",
                table: "Teams",
                column: "Confirmed");

            migrationBuilder.CreateIndex(
                name: "IX_Teams_CtftimeId",
                table: "Teams",
                column: "CtftimeId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Vulnboxes_LandingPageTeamId",
                table: "Vulnboxes",
                column: "LandingPageTeamId",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Vulnboxes");

            migrationBuilder.DropTable(
                name: "Teams");
        }
    }
}
