// <auto-generated />
using System;
using EnoLandingPageBackend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnoLandingPageBackend.Migrations
{
    [DbContext(typeof(LandingPageDatabaseContext))]
    [Migration("20210415134553_m2")]
    partial class m2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EnoLandingPageCore.Database.LandingPageTeam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CtftimeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UniversityAffiliation")
                        .HasColumnType("TEXT");

                    b.Property<long>("VulnboxId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Confirmed");

                    b.HasIndex("CtftimeId")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("EnoLandingPageCore.Database.LandingPageTeamVulnbox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalAddress")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HetznerServerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LandingPageTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootPassword")
                        .HasColumnType("TEXT");

                    b.Property<int>("VulnboxStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LandingPageTeamId")
                        .IsUnique();

                    b.ToTable("Vulnboxes");
                });

            modelBuilder.Entity("EnoLandingPageCore.Database.LandingPageTeamVulnbox", b =>
                {
                    b.HasOne("EnoLandingPageCore.Database.LandingPageTeam", "LandingPageTeam")
                        .WithOne("Vulnbox")
                        .HasForeignKey("EnoLandingPageCore.Database.LandingPageTeamVulnbox", "LandingPageTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandingPageTeam");
                });

            modelBuilder.Entity("EnoLandingPageCore.Database.LandingPageTeam", b =>
                {
                    b.Navigation("Vulnbox")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
